server:
  port: 80

spring:
  cloud:
    sentinel:
      transport:
        # sentinel 地址
        dashboard: 127.0.0.1:8080
        # 接收 sentinel 推送规则
        prot: 8719
    gateway:
      discovery:
        locator:
          # 启用自动根据服务ID建立路由
          enabled: true
          lower-case-service-id: true

logging:
  level:
    root: info

gateway-config:
  open-url:
    GET:
      - /user/login
      - /user/register
    POST:
      - /user/post1
      - /user/post2