server:
  port: 8089

spring:
#  profiles:
#    active: dev
  application:
    name: user
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: 192.168.3.3:8848
        namespace: 2cbda487-8300-4dd5-ac82-b6cb0f985457
        ext-config:
          - data-id: user.yaml
            group: DEFAULT_GROUP
            refresh: true
        file-extension: yaml
      discovery:
        server-addr: 192.168.3.3:8848
        namespace: 2cbda487-8300-4dd5-ac82-b6cb0f985457

#logging:
#  level:
#    root: DEBUG